const messages={
USER_NOT_FOUND:"User not found",
LOG_IN:"User login successfully",
SIGN_UP:"User signup successfully",
ADMIN_LOG_IN:"Admin log in successfull",
SOMETHING_WRONG:"Something went wrong",
OTP_VERIFY:"OTP verify successfull",
OTP_NOT_VERIFY:"Please verify OTP",
OTP_EXPIRED:"OTP time expired",
WRONG_OTP:"OTP not match",
RESEND_OTP:"OTP resend successfully send on email",
FORGOT_PASSWORD:"OTP successfully send on email",
RESET_PASSWORD:"Password reset successfull",
PASSWORD_NOT_MATCH:"Password and  Confirmpassword not match",
PASSWORD_INVALID:"Password not match",
CHANGE_PASSWORD:"Password change successfully",
BOTH_FIELDS_REQUIRED:"Both fields are require",
NO_ALREDY_EXIST:"Mobile number already exist",
MAIL_ALREADY_EXIST:"Email is already exist",
USER_ALREADY:"User already exist",
UNABLE_LOGIN:"Unable to login",
EDIT_PROFILE:"Profile edit successfull",
VIEW:"Profile view successfully",
LIST:"User list successfull",
DATA_VIEW:"User data view successfully",
DELETE:"User delete successfull",
BLOCK:"User block successfully",
STATIC_VIEW:"View static data successfully",
STATIC_ADD:"Add static data successfully",
STATIC_LIST:"Static list successfully",
CONTENET:"Contenet not found",
PRODUCT:"Product unavilable",
PRODUCT_CREATE:"Product show successfully",
PRODUCT_VIEW:"Product view successfully",
PRODUCT_ADD:"Product add successfully",
PRODUCT_NOT:"Product not found",
VENDOR:"Vendor not approved",
VENDOR_APPROVED:"Vendor approved",
WRONG:"Wrong email",
VENDOR_NOT_FOUND:"Vendor not found",
VENDOR_SIGNUP:"Vendor signup successfully",
DELETE_PRODUCT:"Product delete successfully",
PRODUCT_LIST:"Product list",
PRODUCT_LIST_NOT:"Product list not found",
ADD_CART:"Product add to cart"

}
module.exports=messages